// <auto-generated />
using System;
using FnBook.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FnBook.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FnBook.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("noticia_id");

                    b.Property<DateTime?>("AiClassificationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_classificacao_ia");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confianca_ia");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modelo_ia");

                    b.Property<bool?>("AiTruth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verdadeiro_ia");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_conteudo");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("cadastrado_por");

                    b.Property<string>("Embedding")
                        .HasColumnType("TEXT")
                        .HasColumnName("embedding");

                    b.Property<bool?>("FinalTruth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verdadeiro_final");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT")
                        .HasColumnName("justificativa");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("texto");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_verificacao");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("verificado_por");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("visualizacoes");

                    b.HasKey("Id");

                    b.ToTable("Noticia", (string)null);
                });

            modelBuilder.Entity("FnBook.Domain.Entities.NewsOrigin", b =>
                {
                    b.Property<Guid>("OrigemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("origem_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("TEXT")
                        .HasColumnName("noticia_id");

                    b.Property<Guid>("UfId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uf_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("OrigemId");

                    b.HasIndex("NewsId");

                    b.HasIndex("UfId");

                    b.HasIndex("UserId");

                    b.ToTable("Origem", (string)null);
                });

            modelBuilder.Entity("FnBook.Domain.Entities.Uf", b =>
                {
                    b.Property<Guid>("UfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uf_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("sigla");

                    b.HasKey("UfId");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Uf", (string)null);
                });

            modelBuilder.Entity("FnBook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FnBook.Domain.Entities.NewsOrigin", b =>
                {
                    b.HasOne("FnBook.Domain.Entities.News", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FnBook.Domain.Entities.Uf", null)
                        .WithMany()
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FnBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
